---
{{- $name := (include "app-name" $) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $name }}"
spec:
  replicas: {{ $.Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: "{{ $name }}"
  template:
    metadata:
      labels:
        app: "{{ $name }}"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: "{{ $name }}"
      containers:
      - name: echoserver
        image: gijsvandulmen/echoserver:latest
        # command: [ "sleep" ]
        # args: [ "infinity" ]
