---
{{- $name := (include "app-name" $) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $name }}"
spec:
  replicas: {{ $.Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: "{{ $name }}"
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "200m"
        sidecar.istio.io/proxyCPULimit: "300m"
        sidecar.istio.io/proxyMemory: "30Mi"
        sidecar.istio.io/proxyMemoryLimit: "100Mi"
      labels:
        app: "{{ $name }}"
    spec:
      serviceAccountName: less-safe-sa
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: "{{ $name }}"
      containers:
      - name: echoserver
        image: gijsvandulmen/echoserver:latest
        # image: alpine
        # command:
        #   - /bin/sh
        #   - -c
        #   - "sleep infinity"
        env:
          - name: ECHO_SERVER_PORT
            value: "8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
