---
{{- $name := "application-a" -}}
{{- if (($.Values.global | default dict).pr | default dict).branch }}
{{- $name = print "application-a" $.Values.global.pr.number }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $name }}"
spec:
  replicas: {{ $.Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: "{{ $name }}"
  template:
    metadata:
      labels:
        app: "{{ $name }}"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: "{{ $name }}"
      containers:
      - name: alpine
        image: alpine:latest
        command: [ "sleep" ]
        args: [ "infinity" ]
