{{- $name := (include "app-name" $) -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ $name }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ $.Values.domainName }}"
    external-dns.alpha.kubernetes.io/target: "192.168.2.123"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: ingress-gateway
    namespace: istio-ingress
  hostnames: ["{{ $.Values.domainName }}"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ''	
      kind: Service	
      name: "{{ $name }}"
      port: 8080
      weight: 1