---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: application-a-data
spec:
   storageClassName: lvms-vg1
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi