{{- $name := (include "app-name" $) -}}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ $name }}"
  labels:
    app: "{{ $name }}"
    type: custom-domain
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ $.Values.domainName }}"
spec:
  to:
    kind: Service
    name: "{{ $name }}"
  tls:
    {{- if eq $.Values.enableCert "true" }}
    externalCertificate:
      name: subdomain-certs
    {{- else }}
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- end }}
  host: "{{ $.Values.domainName }}"
  port:
    targetPort: 8080
