{{- $name := (include "app-name" $) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}"
  labels:
    app: "{{ $name }}"
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: "{{ $.Values.domainName }}"
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: "{{ $name }}"