{{- $name := (include "app-name" $) -}}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: "{{ $name }}"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       "{{ $name }}"
  updatePolicy:
    updateMode: "Auto"
    evictionRequirements:
    - resources: ["cpu", "memory"]
      changeRequirement: TargetHigherThanRequests